module(
    name = "delay_line",
    version = "0.1.0",
    repo_name = "delay_line",
)

bazel_dep(name = "hdl_rules", version = "0.1.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")

# local_path_override(
#     module_name = "hdl_rules",
#     path = "../hdl_rules",
# )

git_override(
    module_name = "hdl_rules",
    remote = "https://github.com/ErmolaevDmitrii/hdl_rules",
    branch = "main",
)

